#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
python manage.py createsuperuserwithpassword \
        --password mappets \
        --email mappets@mappets.mappets \
        --preserve
python manage.py runserver 0.0.0.0:8000