#!/bin/sh

set -o errexit
set -o nounset


echo 'Starting flower'

celery flower \
    --app=mappets.celery_app \
    --broker="${CELERY_BROKER_URL}" \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
