#!/usr/bin/env bash


### Create a database backup.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) postgres backup


set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


message_welcome "Backing up the '${RDS_DB_NAME}' database..."


if [[ "${RDS_USERNAME}" == "postgres" ]]; then
    message_error "Backing up as 'postgres' user is not supported. Assign 'RDS_USERNAME' env with another one and try again."
    exit 1
fi

export PGHOST="${RDS_HOSTNAME}"
export PGPORT="${RDS_PORT}"
export PGUSER="${RDS_USERNAME}"
export PGPASSWORD="${RDS_PASSWORD}"
export PGDATABASE="${RDS_DB_NAME}"

backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"
pg_dump | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"


message_success "'${RDS_DB_NAME}' database backup '${backup_filename}' has been created and placed in '${BACKUP_DIR_PATH}'."
