version: '3.7'

services:
  web:
    build:
      context: . 
      dockerfile: ./compose/django/Dockerfile
      labels:
        - "django"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ".:/web"
  proxy:
    image: nginx
    ports:
     - "80:80"
    volumes:
      - ./compose/proxy/default.conf:/etc/nginx/conf.d/default.conf
    