version: '3.7'

volumes:
  .postgres_data:
  .postgres_data_backups:
  redis_data: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/dev/postgres/Dockerfile
    image: mappets_postgres
    volumes:
      - .postgres_data:/var/lib/postgresql/data
      - .postgres_data_backups:/backups
    env_file:
      - ./.envs/.dev/.postgres
    ports:
      - "5433:5432"
  django: &django
    build:
      context: . 
      dockerfile: ./compose/dev/django/Dockerfile
      labels:
        - "django"
    volumes:
      - ".:/django"
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
      - ./.envs/.dev/.redis
    command: /start
    depends_on: 
      - postgres
    stdin_open: true
    tty: true
  proxy:
    image: nginx
    ports:
     - "8000:80"
    volumes:
      - ./compose/proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - django
  redis:
    image: 'redis:5.0-alpine'
    volumes:
      - 'redis_data:/data'
    env_file:
      - ./.envs/.dev/.redis
    ports:
      - "6380:6379"
    depends_on:
      - postgres