# Generated by Django 2.1.7 on 2019-08-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=50, verbose_name='Endereço')),
                ('latitude', models.CharField(default=None, max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(default=None, max_length=50, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('color', models.CharField(choices=[('P', 'PRETO'), ('B', 'BRANCO'), ('L', 'LARANJA'), ('M', 'MARROM'), ('BI', 'BICOLOR'), ('TRI', 'TRICOLOR')], max_length=20, verbose_name='Cor')),
                ('gender', models.CharField(choices=[('f', 'Femeas'), ('m', 'Macho')], max_length=1, verbose_name='Sexo')),
                ('size', models.CharField(choices=[('PQ', 'PEQUENO'), ('MD', 'MEDIO'), ('GR', 'GRANDE')], default='MD', max_length=50, verbose_name='Porte')),
                ('species', models.CharField(choices=[('C', 'CACHORRO'), ('G', 'GATO')], max_length=1, verbose_name='Espécie')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Breed', verbose_name='Raça')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
            },
        ),
        migrations.AddField(
            model_name='history',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.Pet', verbose_name='Histórico do Pet'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='Usuário'),
        ),
    ]
