# Generated by Django 2.2.13 on 2020-07-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='latitude',
            field=models.FloatField(default=None, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='history',
            name='longitude',
            field=models.FloatField(default=None, verbose_name='Longitude'),
        ),
    ]
