# Generated by Django 2.2.13 on 2020-09-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
