# Generated by Django 2.1.7 on 2019-02-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('color', models.CharField(choices=[('P', 'PRETO'), ('B', 'BRANCO'), ('L', 'LARANJA'), ('M', 'MARROM'), ('BI', 'BICOLOR'), ('TRI', 'TRICOLOR')], max_length=20)),
                ('gender', models.CharField(choices=[('f', 'Femea'), ('m', 'Macho')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feature', models.CharField(max_length=50, null=True, verbose_name='Característica')),
                ('size', models.CharField(choices=[('PQ', 'PEQUENO'), ('MD', 'MEDIO'), ('GR', 'GRANDE')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Breed', verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Species', verbose_name='Espécie'),
        ),
    ]
