# Generated by Django 2.1.7 on 2019-02-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Raça', 'verbose_name_plural': 'Raças'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
        migrations.RemoveField(
            model_name='species',
            name='size',
        ),
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('PQ', 'PEQUENO'), ('MD', 'MEDIO'), ('GR', 'GRANDE')], default='MD', max_length=50, verbose_name='Porte'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(choices=[('P', 'PRETO'), ('B', 'BRANCO'), ('L', 'LARANJA'), ('M', 'MARROM'), ('BI', 'BICOLOR'), ('TRI', 'TRICOLOR')], max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('f', 'Femea'), ('m', 'Macho')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='animalhistory',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name='Histórico do Animal'),
        ),
    ]
