# Generated by Django 2.1.7 on 2019-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_auto_20190219_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('C', 'CACHORRO'), ('G', 'GATO')], max_length=1, verbose_name='Espécie'),
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
