# Generated by Django 2.1.7 on 2019-02-19 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('animal', '0003_auto_20190219_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalhistory',
            name='address',
            field=models.CharField(default=None, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='animalhistory',
            name='latitude',
            field=models.CharField(default=None, max_length=50, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='animalhistory',
            name='longitude',
            field=models.CharField(default=None, max_length=50, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='animalhistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Usuário'),
        ),
    ]
