# Generated by Django 2.2.13 on 2020-07-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('organizations', models.ManyToManyField(to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
